FROM node:10.15-alpine

# Update alpine packages
RUN apk update add --no-cache yarn 

# Add pm2
RUN yarn global add pm2 && \
  mkdir /backend

COPY . /backend

# Enter backend dir
WORKDIR /backend
# install modules 
RUN yarn install
# Start process
CMD tail -f /dev/null